function FILEPATHS = filepaths(IMDIR, IMBASE, NDIGITS, EXT, START, STOP)
% FILEPATHS creates a vector whose rows contain the paths to
% sequentially numbered files. The paths generated by FILEPATHS do not
% need to exist for the function to operate
%
% INPUTS
%   IMDIR = Path to directory in which images are located (string).
%
%   IMBASE = Image base name (i.e., part of the image name that preceeds
%   image numbers) (string).
%
%   NDIGITS = Number of digits in the image number suffix (integer)
%
%   EXT = Image extension, including 'dot' (example: EXT = '.tif') (string)
%
%   START = Number of the first image in the sequence (integer)
%
%   STOP = Number of the final image in the sequence (integer)
%
% OUTPUTS
%   FILEPATHS = Matrix whose rows are strings containing the file paths to
%   each image in the specified sequence.
% 
% SEE ALSO
%   fullfile

%%%%%%%%%%%%%%%%%%%%%%
%%% BEGIN FUNCTION %%%
%%%%%%%%%%%%%%%%%%%%%%

depth = STOP - START + 1; % Number of images

% Format sprintf argument for specified number of zeros
form = ['%0' num2str(NDIGITS) '.0f'];

% Create array of strings containing names of raw images and of masks
for i = 1: depth
   FILEPATHS(i, :) = fullfile(IMDIR, [IMBASE sprintf(form, START + i - 1) EXT]);
end

end

%%%%%%%%%%%%%%%%%%%%
%%% END FUNCTION %%%
%%%%%%%%%%%%%%%%%%%%

